with open("input.txt","r") as f:
    x=map(int,f.readline())
    l1=(list(x))
    print("lista 1=",lista1)
    l2=sorted(l1)
    print("lista crescator=",lista2)
    lista3=list(x)
    lista3.sort(reverse=True)
    print("lista sortata descrescator =",lista3)
    print("numarul de elemente din lista=",len(lista1))
    print("MAX =",max(lista1))
    print("MIN =",min(lista1))
    lista4=list(x)
    lista4.extend([111])
    print("lista nou formata cu adaugarea 111 =",lista4)
    lista5=list(x)
    lista5.insert(2,222)
    print("lista nou formata cu adaugarea 222 =",lista5)